name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ lcov

    - name: Build Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Build Google Benchmark
      run: |
        git clone https://github.com/google/benchmark.git
        cd benchmark
        git clone https://github.com/google/googletest.git
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        sudo make install

    - name: Create build directory
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure

    - name: Run benchmarks
      run: cd build && ./cramer_benchmarks
