name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y cmake lcov libgtest-dev

      - name: Install GTest
        run: |
          cd /usr/src/gtest
          sudo cmake -B build
          sudo cmake --build build
          sudo cp build/lib/*.a /usr/lib

      - name: Install Google Benchmark
        run: |
          git clone https://github.com/google/benchmark.git
          cd benchmark
          git clone https://github.com/google/googletest.git
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make

      - name: Run tests
        run: |
          cd build
          ctest

      - name: Generate coverage report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: build/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
