name: Document

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen
    - name: Generate Documentation
      run: doxygen Doxyfile
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
